const estimateResponses = [
  "Oh you sweet, delusional summer child! Your time estimate is wronger than pineapple on pizza debates. Double it, add six months of existential crisis, and maybe you'll be close.",
  "Haha, bless your optimistic little heart! That estimate just got laughed out of the room by reality. This project will take longer than it took to build the pyramids... with fewer slaves and more coffee.",
  "Buddy, your timeline is cuter than a puppy trying to code. Newsflash: it's wrong! Expect scope creep so bad you'll name your next kid 'Bugfix'.",
  "Wrong? Understatement of the century! Your estimate is so off, it's orbiting a different planet. Welcome to debugging hell – population: your weekends.",
  "Aww, look at you with your adorable little estimate. It's wrong, champ. This thing's gonna multiply like rabbits on steroids and eat your social life alive.",
  "You're not estimating, you're fantasizing! That time is wrong by a factor of 'oh shit'. Prepare for all-nighters that make vampires jealous.",
  "Hilarious! Your estimate died a painful death the second you submitted it. Real talk: triple it and sacrifice a goat to the PM gods.",
  "You absolute legend of wishful thinking! Wrong estimate alert. This project will outlast your New Year's resolutions and your motivation combined.",
  "Sweet baby coder, that timeline is faker than reality TV. It's wrong – expect to finish right around the time pigs learn to fly and your boss stops asking for updates.",
  "Lmao, in what universe does that estimate live? Ours? Nope. Reality says multiply by 4, add therapy sessions, subtract your hairline.",
  "Adorable optimism! But nah, your estimate is dead wrong. This bad boy will have more twists than a M. Night Shyamalan movie, and zero happy endings.",
  "Rookie mistake, my friend. Your time guess is so wrong it's embarrassing. Double everything and throw in a mid-project identity crisis for flavor.",
  "Oh honey, no. That estimate is wronger than my last diet. The project gods are laughing – you'll be done sometime after the heat death of the universe.",
  "Your brain must've taken a vacation when you came up with that. Estimate = wrong! Expect feature creep so wild it'll make your hair stand on end... what's left of it.",
  "Haha good one! But seriously, your estimate is tragically incorrect. This will consume your life faster than TikTok scrolls through your attention span.",
  "Bless your heart, you beautiful naive soul. Wrong estimate! Multiply by pi, round up to the next apocalypse, and add regret.",
  "That's not an estimate, that's a cry for help in disguise. It's wrong, dude. Your project is about to go full 'Lord of the Rings' – epic journey, zero hobbits.",
  "Optimism level: expert. Accuracy level: dumpster fire. Your time estimate is hilariously wrong – enjoy the ride into overtime oblivion.",
  "You and your estimate are in a toxic relationship with reality. Spoiler: it's wrong and breaking up is messy. Expect delays longer than DMV lines.",
  "Cute! But that timeline just got vetoed by the universe. Wrong AF. This project will teach you humility the hard way, with extra bugs.",
  "In the words of every dev ever: 'It'll be quick!' Famous last words. Your estimate is wrong – triple it or prepare to cry in the club (of unfinished tasks).",
  "Your estimate is so wrong, it owes me money for emotional damage. Get ready for a marathon where the finish line keeps moving like a glitchy video game.",
  "Legend says only fools and newbies give such estimates. Congrats, you're both! Wrong – this will take forever plus one day of 'just one more fix'.",
  "Aww, did you consult a magic 8-ball for that time? Because it's wrong. Reality check: double it, add coffee IV, lose sleep, repeat.",
  "Your time estimate walked into a bar... and got rejected harder than your last Tinder date. It's wrong! The project wins this round, champ.",
  "Oh bless your sweet delusional heart! That time estimate is cuter than a puppy trying to do calculus—and just as wrong.",
  "Haha, good joke! But seriously, your timeline is so optimistic it makes Elon Musk's Mars plans look realistic.",
  "Sweet summer child, thinking it'll take that? Reality is coming for you with a baseball bat labeled 'scope creep'.",
  "That's not an estimate, that's a cry for help from your future sleep-deprived self.",
  "Adorable! You estimated like someone who's never met a single unexpected bug in their life.",
  "Your time estimate is wronger than pineapple on pizza debates. Prepare for triple the time plus regret.",
  "Cute! Did you calculate that while ignoring all of human history's project disasters?",
  "Buddy, multiply your estimate by pi, add infinite coffee, and subtract your will to live. Still wrong.",
  "You're not a project estimator, you're a professional daydreamer. The actual time laughs at your naivety.",
  "That estimate is shorter than a TikTok attention span. This project will haunt you longer than a bad ex.",
  "Congratulations! You've discovered the most optimistic fiction since 'this meeting could have been an email'.",
  "Thinking your estimate is enough? Even Santa takes longer to deliver presents, and he has magic.",
  "Your estimate just got absolutely bodied by Murphy's Law. Welcome to the pain Olympics.",
  "Aw, you forgot about the meetings, the 'quick fixes' that aren't, and the existential dread? Classic rookie move.",
  "This isn't going to take your estimate. It's going to take the time it takes to question all your life choices.",
  "Your timeline is so wrong, it's filing for divorce from reality and taking half your weekends.",
  "Bless up! You estimated with the confidence of a man who thinks 'one more episode' ever ends well.",
  "That's hilarious. The project will actually finish right after the heat death of the universe.",
  "You sweet, innocent fool. This will expand faster than my to-do list after New Year's resolutions.",
  "Estimate rejected! Actual duration: 'whenever the coding gods stop laughing at your plans'.",
  "Like a kid guessing how many jellybeans in the jar—adorably, hilariously incorrect.",
  "Your time estimate is wrong, and your future self is already drafting the strongly-worded complaint letter to past you.",
  "C'mon man, even Gandalf knows 'you shall not pass' deadlines that easily.",
  "That's not planning, that's manifesting failure with extra steps and a side of delusion.",
  "Prepare thy anus, because this project is about to take longer than a Game of Thrones finale season.",
];
