const estimateResponses = [
  "Holy fucking shit, did you just pull that time estimate straight out of your ass? It's wrong, you delusional walnut.",
  "Aww, look at this precious little dreamer thinking their estimate means anything. Wrong. Painfully, embarrassingly wrong.",
  "Bro your optimism is cute... like a goldfish trying to do quantum physics. Your estimate is dogshit wrong.",
  "Your time estimate is so bad it makes flat-earthers look like geniuses. Multiply it by 12 and add crippling regret.",
  "Congratulations! You've achieved peak delusion. That estimate is not just wrong, it's an insult to mathematics itself.",
  "Sweet baby Jesus, you actually believe that timeline? The universe is laughing at you harder than I am.",
  "That estimate is cuter than a kitten... and about as useful as one for project planning. Completely fucking wrong.",
  "You didn't estimate the time, you wrote fanfiction. Tragic. Wrong on every possible level.",
  "Bless your smooth brain for thinking that would be enough time. Reality called — it's filing a restraining order.",
  "Your estimate is wronger than your ex's 'it's not you, it's me'. This project is about to destroy your soul.",
  "Did you calculate that during a fever dream? Because it's hilariously, catastrophically incorrect.",
  "You're not a developer, you're a professional copium inhaler. That time estimate is straight garbage.",
  "The confidence to submit that estimate should be studied. Too bad the accuracy is nonexistent.",
  "Your timeline is so optimistic it should run for president. Unfortunately it's still dead wrong.",
  "Oh honey... no. Just no. Your estimate is wrong and your future self hates you for it.",
  "That's the cutest little wrong estimate I've seen all week. Multiply by 7 and prepare to suffer.",
  "You estimated like someone who has never been punched in the face by reality. Welcome to your first beating.",
  "Lmao this estimate is so bad I'm saving it for my comedy special. It's wrong, dumbass.",
  "Your brain must have been on airplane mode when you wrote that. Estimate rejected by the laws of physics.",
  "Adorable. You thought this would take that long? The project gods are roasting you harder than this.",
  "That time estimate just got absolutely violated by common sense. Try again, clown.",
  "You're the type of person who says '5 more minutes' and shows up 3 hours late. Your estimate reflects that.",
  "This isn't planning, this is self-harm with extra steps. Your estimate is laughably terrible.",
  "Even my grandma's bingo predictions are more accurate than this dumpster fire of a timeline.",
  "Bro you didn't estimate shit. You had a hallucination and typed numbers. All wrong.",
  "Your estimate is so wrong it's actually offensive. The bugs are already laughing at you.",
  "Thinking it'll only take that? Bold of you to assume the universe won't personally fuck you over.",
  "Peak performance in delusion. Your time estimate deserves an Oscar for Best Comedy.",
  "You sweet summer child with the IQ of a soggy potato. That estimate is tragically incorrect.",
  "This estimate belongs in the trash along with your hopes and dreams for this weekend.",
  "Your timeline is faker than Instagram models. Wrong. So very wrong it hurts.",
  "Did ChatGPT give you that estimate? Because even AI wouldn't be this confidently stupid.",
  "The only thing more wrong than your estimate is your taste in project management.",
  "You're about to learn why developers drink. Spoiler: because of idiots like your current estimate.",
  "That number you wrote? Pure fiction. Worse than Twilight. At least that had vampires.",
  "Your estimate is so bad, Murphy's Law just sent it a thank you card.",
  "Bless your heart, you absolute walnut. This project will take three times longer and destroy your sleep.",
  "You estimated with the same energy as 'this diet starts Monday'. We all know how that ends.",
  "This timeline is so wrong it's circling back around to performance art. Tragic.",
  "Your project estimate is what happens when hope fucks ignorance and gives birth to stupidity.",
  "Even a broken clock is right twice a day. Your estimate somehow managed to be wrong 24/7.",
  "You're not estimating time, you're writing a fantasy novel with terrible plot holes.",
  "That estimate died faster than your motivation after the first bug. It's wrong.",
  "The audacity of this estimate is actually impressive. Too bad it's completely braindead.",
  "Your future self is already crying in the corner because of this hilariously wrong estimate.",
  "This is why we can't have nice things. Because people like you submit estimates like this.",
  "Your time estimate is so off it's in a different timezone. One called 'Pain'.",
  "Congrats on creating the most optimistic piece of fiction since 'The Project Will Be On Time'.",
  "You're gonna need a bigger estimate... and therapy after this project murders your soul.",
  "That estimate is wronger than trying to put socks on a rooster. Absolute clownery.",
  "Reality is going to hit you so hard you'll see stars. Your estimate is the first casualty.",
  "You wrote that with your eyes closed, didn't you? Because it's blind levels of wrong.",
  "This estimate is the software equivalent of 'the check is in the mail'. Bullshit.",
  "Your timeline just got yeeted into the sun by actual project experience.",
  "Bold move submitting that. Stupid move, but bold. It's wrong as hell.",
  "The only thing shorter than your estimate is your attention span during debugging.",
  "You absolute donut. That time estimate belongs in the bin with yesterday's garbage.",
  "This project is about to stretch longer than your excuses for being late.",
  "Your estimate is cute... in the same way a trainwreck is entertaining.",
  "Even Santa has more realistic delivery timelines than whatever the fuck this is.",
  "That estimate is so wrong, it needs its own support group for failed predictions.",
  "You're the reason why 'it'll be done by Friday' is the biggest lie in tech.",
  "Hope you like sleeping with your laptop because this estimate is pure delusion.",
  "Your time calculation skills are worse than a drunk toddler with a calculator.",
  "This estimate is what happens when arrogance meets zero experience.",
  "The bugs haven't even started and your estimate is already dead on arrival.",
  "You're about to get absolutely violated by scope creep, thanks to this joke of an estimate.",
  "That number you picked? My sides are in orbit from how wrong it is.",
  "Professional developers are laughing. Your estimate is comedy gold.",
  "You didn't estimate the project, you insulted it with that pathetic timeline.",
  "This is why project managers drink. Because of estimates like yours.",
  "Your timeline is so short it should come with training wheels.",
  "Even unicorns and rainbows have more realistic deadlines than this shit.",
  "Prepare to become one with the chair because this estimate is a total lie.",
  "That estimate is wronger than a vegan at a barbecue contest.",
  "You've got the confidence of a star and the accuracy of a participation trophy.",
  "This project will take so long you'll forget what sunlight feels like.",
  "Your estimate just got friendzoned by reality. Harsh.",
  "Thinking that's enough time is the funniest joke I've heard this year.",
  "The coding gods just sacrificed a goat because your estimate offended them so much.",
  "You're not a planner, you're a chaos agent with extra steps.",
  "That estimate is so bad it made me spill my coffee from laughing.",
  "Future you is writing a very angry letter to present you right now.",
  "This is what peak performance in clownery looks like. Terrible estimate.",
  "Your timeline belongs in the fiction section next to Harry Potter.",
  "Even a magic 8-ball gives better project predictions than you.",
  "Hope you're ready to sell your soul because this estimate ain't cutting it.",
  "That estimate is weaker than your excuses for missing deadlines.",
  "You've successfully estimated nothing. Absolute zero accuracy achieved.",
  "The only thing this estimate is good for is toilet paper.",
  "You're about to enter the 'why did I think this would be quick' phase of grief.",
  "This estimate is so wrong it looped back and became performance art.",
  "Congrats, you've invented a new level of delusion previously thought impossible.",
  "Your project is going to take longer than it took to make the entire Marvel universe.",
  "That estimate just got absolutely mogged by basic common sense.",
  "Prepare thy butthole, because reality is coming in dry with this estimate.",
  "You're the human equivalent of optimistic error messages.",
  "This timeline is faker than a Kardashian's ass. Completely wrong.",
  "Even Nostradamus is facepalming at how terrible your estimate is."
];